use_frameworks!

target 'Vetty_Example' do
  pod 'Vetty', :path => '../'
  pod 'Texture'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxAlamofire'
  pod 'RxOptional'
  
  target 'Vetty_Tests' do
    inherit! :search_paths
    pod "Quick"
    pod "Nimble"
    pod 'RxTest'
    pod 'RxBlocking'
  end
end
