language: objective-c
osx_image: xcode10

cache: cocoapods
podfile: Example/Podfile

before_install:
  - pod install --repo-update --project-directory=Example
  
branches:
  only:
    - master
    
script:
- xcodebuild clean -workspace Example/Vetty.xcworkspace -scheme Vetty | xcpretty
- xcodebuild build -sdk iphonesimulator -workspace Example/Vetty.xcworkspace -scheme Vetty CODE_SIGNING_REQUIRED=NO | xcpretty